name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init submodules
      run: |
        git submodule init
        git submodule update

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Install deps
      run: sudo apt install -y lcov

    - name: Generate code coverage report
      run: |
        lcov --directory . --capture --rc lcov_branch_coverage=1 -q --output-file coverage.info --exclude '*unity.c'
        genhtml -q --rc genhtml_branch_coverage=1 --output-directory coverage coverage.info

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/
